platform: Any CPU
configuration: Release
version: 1.0.{build}

assembly_info:
  patch: true
  file: '**\AssemblyInfo.cs'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

build:
  publish_nuget: true
  parallel: true
  project: ModernDev.Dice.sln

before_build:
  - nuget restore

deploy:
- provider: NuGet
  api_key:
    secure: VgpA4NJgZjB689R1BP3A4bbtQzjprU8U/Cgre7NS5IDWxry5Z9WxhFUqz8lWsRnw
  artifact: /.*\.nupkg/

after_build:
  - nuget pack ModernDev.Dice.nuspec -version %APPVEYOR_BUILD_VERSION%
  - appveyor PushArtifact ModernDev.Dice.%APPVEYOR_BUILD_VERSION%.nupkg

notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/fa03538b00d66941afee
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true