//
// This file\code is part of InTouch project.
//
// InTouch - is a .NET wrapper for the vk.com API.
// https://github.com/virtyaluk/InTouch
//
// Copyright (c) 2016 Bohdan Shtepan
// http://modern-dev.com/
//
// Licensed under the MIT license.
//

using System;
using System.Collections.Generic;

namespace ModernDev.Dice
{
    public partial class Dice
    {
        internal static class Data
        {
            public const string Numbers = "0123456789";
            public const string CharsLower = "abcdefghijklmnopqrstuvwxyz";
            public static readonly string CharsUpper = CharsLower.ToUpperInvariant();
            public const string HexPool = Numbers + "abcdef";

            public static readonly List<Tuple<string, string, string, int>> Months = new List
                <Tuple<string, string, string, int>>
            {
                {"January", "Jan", "01", 31},
                {"February", "Feb", "02", 28},
                {"March", "Mar", "03", 31},
                {"April", "Apr", "04", 30},
                {"May", "May", "05", 31},
                {"June", "Jun", "06", 30},
                {"July", "Jul", "07", 31},
                {"August", "Aug", "08", 31},
                {"September", "Sep", "09", 30},
                {"October", "Oct", "10", 31},
                {"November", "Nov", "11", 30},
                {"December", "Dec", "12", 31}
            };

            public static readonly List<string> FirstNamesMale = new List<string>
            {
                "James",
                "John",
                "Robert",
                "Michael",
                "William",
                "David",
                "Richard",
                "Joseph",
                "Charles",
                "Thomas",
                "Christopher",
                "Daniel",
                "Matthew",
                "George",
                "Donald",
                "Anthony",
                "Paul",
                "Mark",
                "Edward",
                "Steven",
                "Kenneth",
                "Andrew",
                "Brian",
                "Joshua",
                "Kevin",
                "Ronald",
                "Timothy",
                "Jason",
                "Jeffrey",
                "Frank",
                "Gary",
                "Ryan",
                "Nicholas",
                "Eric",
                "Stephen",
                "Jacob",
                "Larry",
                "Jonathan",
                "Scott",
                "Raymond",
                "Justin",
                "Brandon",
                "Gregory",
                "Samuel",
                "Benjamin",
                "Patrick",
                "Jack",
                "Henry",
                "Walter",
                "Dennis",
                "Jerry",
                "Alexander",
                "Peter",
                "Tyler",
                "Douglas",
                "Harold",
                "Aaron",
                "Jose",
                "Adam",
                "Arthur",
                "Zachary",
                "Carl",
                "Nathan",
                "Albert",
                "Kyle",
                "Lawrence",
                "Joe",
                "Willie",
                "Gerald",
                "Roger",
                "Keith",
                "Jeremy",
                "Terry",
                "Harry",
                "Ralph",
                "Sean",
                "Jesse",
                "Roy",
                "Louis",
                "Billy",
                "Austin",
                "Bruce",
                "Eugene",
                "Christian",
                "Bryan",
                "Wayne",
                "Russell",
                "Howard",
                "Fred",
                "Ethan",
                "Jordan",
                "Philip",
                "Alan",
                "Juan",
                "Randy",
                "Vincent",
                "Bobby",
                "Dylan",
                "Johnny",
                "Phillip",
                "Victor",
                "Clarence",
                "Ernest",
                "Martin",
                "Craig",
                "Stanley",
                "Shawn",
                "Travis",
                "Bradley",
                "Leonard",
                "Earl",
                "Gabriel",
                "Jimmy",
                "Francis",
                "Todd",
                "Noah",
                "Danny",
                "Dale",
                "Cody",
                "Carlos",
                "Allen",
                "Frederick",
                "Logan",
                "Curtis",
                "Alex",
                "Joel",
                "Luis",
                "Norman",
                "Marvin",
                "Glenn",
                "Tony",
                "Nathaniel",
                "Rodney",
                "Melvin",
                "Alfred",
                "Steve",
                "Cameron",
                "Chad",
                "Edwin",
                "Caleb",
                "Evan",
                "Antonio",
                "Lee",
                "Herbert",
                "Jeffery",
                "Isaac",
                "Derek",
                "Ricky",
                "Marcus",
                "Theodore",
                "Elijah",
                "Luke",
                "Jesus",
                "Eddie",
                "Troy",
                "Mike",
                "Dustin",
                "Ray",
                "Adrian",
                "Bernard",
                "Leroy",
                "Angel",
                "Randall",
                "Wesley",
                "Ian",
                "Jared",
                "Mason",
                "Hunter",
                "Calvin",
                "Oscar",
                "Clifford",
                "Jay",
                "Shane",
                "Ronnie",
                "Barry",
                "Lucas",
                "Corey",
                "Manuel",
                "Leo",
                "Tommy",
                "Warren",
                "Jackson",
                "Isaiah",
                "Connor",
                "Don",
                "Dean",
                "Jon",
                "Julian",
                "Miguel",
                "Bill",
                "Lloyd",
                "Charlie",
                "Mitchell",
                "Leon",
                "Jerome",
                "Darrell",
                "Jeremiah",
                "Alvin",
                "Brett",
                "Seth",
                "Floyd",
                "Jim",
                "Blake",
                "Micheal",
                "Gordon",
                "Trevor",
                "Lewis",
                "Erik",
                "Edgar",
                "Vernon",
                "Devin",
                "Gavin",
                "Jayden",
                "Chris",
                "Clyde",
                "Tom",
                "Derrick",
                "Mario",
                "Brent",
                "Marc",
                "Herman",
                "Chase",
                "Dominic",
                "Ricardo",
                "Franklin",
                "Maurice",
                "Max",
                "Aiden",
                "Owen",
                "Lester",
                "Gilbert",
                "Elmer",
                "Gene",
                "Francisco",
                "Glen",
                "Cory",
                "Garrett",
                "Clayton",
                "Sam",
                "Jorge",
                "Chester",
                "Alejandro",
                "Jeff",
                "Harvey",
                "Milton",
                "Cole",
                "Ivan",
                "Andre",
                "Duane",
                "Landon"
            };

            public static readonly List<string> FirstNamesFemale = new List<string>
            {
                "Mary",
                "Emma",
                "Elizabeth",
                "Minnie",
                "Margaret",
                "Ida",
                "Alice",
                "Bertha",
                "Sarah",
                "Annie",
                "Clara",
                "Ella",
                "Florence",
                "Cora",
                "Martha",
                "Laura",
                "Nellie",
                "Grace",
                "Carrie",
                "Maude",
                "Mabel",
                "Bessie",
                "Jennie",
                "Gertrude",
                "Julia",
                "Hattie",
                "Edith",
                "Mattie",
                "Rose",
                "Catherine",
                "Lillian",
                "Ada",
                "Lillie",
                "Helen",
                "Jessie",
                "Louise",
                "Ethel",
                "Lula",
                "Myrtle",
                "Eva",
                "Frances",
                "Lena",
                "Lucy",
                "Edna",
                "Maggie",
                "Pearl",
                "Daisy",
                "Fannie",
                "Josephine",
                "Dora",
                "Rosa",
                "Katherine",
                "Agnes",
                "Marie",
                "Nora",
                "May",
                "Mamie",
                "Blanche",
                "Stella",
                "Ellen",
                "Nancy",
                "Effie",
                "Sallie",
                "Nettie",
                "Della",
                "Lizzie",
                "Flora",
                "Susie",
                "Maud",
                "Mae",
                "Etta",
                "Harriet",
                "Sadie",
                "Caroline",
                "Katie",
                "Lydia",
                "Elsie",
                "Kate",
                "Susan",
                "Mollie",
                "Alma",
                "Addie",
                "Georgia",
                "Eliza",
                "Lulu",
                "Nannie",
                "Lottie",
                "Amanda",
                "Belle",
                "Charlotte",
                "Rebecca",
                "Ruth",
                "Viola",
                "Olive",
                "Amelia",
                "Hannah",
                "Jane",
                "Virginia",
                "Emily",
                "Matilda",
                "Irene",
                "Kathryn",
                "Esther",
                "Willie",
                "Henrietta",
                "Ollie",
                "Amy",
                "Rachel",
                "Sara",
                "Estella",
                "Theresa",
                "Augusta",
                "Ora",
                "Pauline",
                "Josie",
                "Lola",
                "Sophia",
                "Leona",
                "Anne",
                "Mildred",
                "Ann",
                "Beulah",
                "Callie",
                "Lou",
                "Delia",
                "Eleanor",
                "Barbara",
                "Iva",
                "Louisa",
                "Maria",
                "Mayme",
                "Evelyn",
                "Estelle",
                "Nina",
                "Betty",
                "Marion",
                "Bettie",
                "Dorothy",
                "Luella",
                "Inez",
                "Lela",
                "Rosie",
                "Allie",
                "Millie",
                "Janie",
                "Cornelia",
                "Victoria",
                "Ruby",
                "Winifred",
                "Alta",
                "Celia",
                "Christine",
                "Beatrice",
                "Birdie",
                "Harriett",
                "Mable",
                "Myra",
                "Sophie",
                "Tillie",
                "Isabel",
                "Sylvia",
                "Carolyn",
                "Isabelle",
                "Leila",
                "Sally",
                "Ina",
                "Essie",
                "Bertie",
                "Nell",
                "Alberta",
                "Katharine",
                "Lora",
                "Rena",
                "Mina",
                "Rhoda",
                "Mathilda",
                "Abbie",
                "Eula",
                "Dollie",
                "Hettie",
                "Eunice",
                "Fanny",
                "Ola",
                "Lenora",
                "Adelaide",
                "Christina",
                "Lelia",
                "Nelle",
                "Sue",
                "Johanna",
                "Lilly",
                "Lucinda",
                "Minerva",
                "Lettie",
                "Roxie",
                "Cynthia",
                "Helena",
                "Hilda",
                "Hulda",
                "Bernice",
                "Genevieve",
                "Jean",
                "Cordelia",
                "Marian",
                "Francis",
                "Jeanette",
                "Adeline",
                "Gussie",
                "Leah",
                "Lois",
                "Lura",
                "Mittie",
                "Hallie",
                "Isabella",
                "Olga",
                "Phoebe",
                "Teresa",
                "Hester",
                "Lida",
                "Lina",
                "Winnie",
                "Claudia",
                "Marguerite",
                "Vera",
                "Cecelia",
                "Bess",
                "Emilie",
                "John",
                "Rosetta",
                "Verna",
                "Myrtie",
                "Cecilia",
                "Elva",
                "Olivia",
                "Ophelia",
                "Georgie",
                "Elnora",
                "Violet",
                "Adele",
                "Lily",
                "Linnie",
                "Loretta",
                "Madge",
                "Polly",
                "Virgie",
                "Eugenia",
                "Lucile",
                "Lucille",
                "Mabelle",
                "Rosalie"
            };

            public static readonly List<string> LastNames = new List<string>
            {
                "Smith",
                "Johnson",
                "Williams",
                "Jones",
                "Brown",
                "Davis",
                "Miller",
                "Wilson",
                "Moore",
                "Taylor",
                "Anderson",
                "Thomas",
                "Jackson",
                "White",
                "Harris",
                "Martin",
                "Thompson",
                "Garcia",
                "Martinez",
                "Robinson",
                "Clark",
                "Rodriguez",
                "Lewis",
                "Lee",
                "Walker",
                "Hall",
                "Allen",
                "Young",
                "Hernandez",
                "King",
                "Wright",
                "Lopez",
                "Hill",
                "Scott",
                "Green",
                "Adams",
                "Baker",
                "Gonzalez",
                "Nelson",
                "Carter",
                "Mitchell",
                "Perez",
                "Roberts",
                "Turner",
                "Phillips",
                "Campbell",
                "Parker",
                "Evans",
                "Edwards",
                "Collins",
                "Stewart",
                "Sanchez",
                "Morris",
                "Rogers",
                "Reed",
                "Cook",
                "Morgan",
                "Bell",
                "Murphy",
                "Bailey",
                "Rivera",
                "Cooper",
                "Richardson",
                "Cox",
                "Howard",
                "Ward",
                "Torres",
                "Peterson",
                "Gray",
                "Ramirez",
                "James",
                "Watson",
                "Brooks",
                "Kelly",
                "Sanders",
                "Price",
                "Bennett",
                "Wood",
                "Barnes",
                "Ross",
                "Henderson",
                "Coleman",
                "Jenkins",
                "Perry",
                "Powell",
                "Long",
                "Patterson",
                "Hughes",
                "Flores",
                "Washington",
                "Butler",
                "Simmons",
                "Foster",
                "Gonzales",
                "Bryant",
                "Alexander",
                "Russell",
                "Griffin",
                "Diaz",
                "Hayes",
                "Myers",
                "Ford",
                "Hamilton",
                "Graham",
                "Sullivan",
                "Wallace",
                "Woods",
                "Cole",
                "West",
                "Jordan",
                "Owens",
                "Reynolds",
                "Fisher",
                "Ellis",
                "Harrison",
                "Gibson",
                "McDonald",
                "Cruz",
                "Marshall",
                "Ortiz",
                "Gomez",
                "Murray",
                "Freeman",
                "Wells",
                "Webb",
                "Simpson",
                "Stevens",
                "Tucker",
                "Porter",
                "Hunter",
                "Hicks",
                "Crawford",
                "Henry",
                "Boyd",
                "Mason",
                "Morales",
                "Kennedy",
                "Warren",
                "Dixon",
                "Ramos",
                "Reyes",
                "Burns",
                "Gordon",
                "Shaw",
                "Holmes",
                "Rice",
                "Robertson",
                "Hunt",
                "Black",
                "Daniels",
                "Palmer",
                "Mills",
                "Nichols",
                "Grant",
                "Knight",
                "Ferguson",
                "Rose",
                "Stone",
                "Hawkins",
                "Dunn",
                "Perkins",
                "Hudson",
                "Spencer",
                "Gardner",
                "Stephens",
                "Payne",
                "Pierce",
                "Berry",
                "Matthews",
                "Arnold",
                "Wagner",
                "Willis",
                "Ray",
                "Watkins",
                "Olson",
                "Carroll",
                "Duncan",
                "Snyder",
                "Hart",
                "Cunningham",
                "Bradley",
                "Lane",
                "Andrews",
                "Ruiz",
                "Harper",
                "Fox",
                "Riley",
                "Armstrong",
                "Carpenter",
                "Weaver",
                "Greene",
                "Lawrence",
                "Elliott",
                "Chavez",
                "Sims",
                "Austin",
                "Peters",
                "Kelley",
                "Franklin",
                "Lawson",
                "Fields",
                "Gutierrez",
                "Ryan",
                "Schmidt",
                "Carr",
                "Vasquez",
                "Castillo",
                "Wheeler",
                "Chapman",
                "Oliver",
                "Montgomery",
                "Richards",
                "Williamson",
                "Johnston",
                "Banks",
                "Meyer",
                "Bishop",
                "McCoy",
                "Howell",
                "Alvarez",
                "Morrison",
                "Hansen",
                "Fernandez",
                "Garza",
                "Harvey",
                "Little",
                "Burton",
                "Stanley",
                "Nguyen",
                "George",
                "Jacobs",
                "Reid",
                "Kim",
                "Fuller",
                "Lynch",
                "Dean",
                "Gilbert",
                "Garrett",
                "Romero",
                "Welch",
                "Larson",
                "Frazier",
                "Burke",
                "Hanson",
                "Day",
                "Mendoza",
                "Moreno",
                "Bowman",
                "Medina",
                "Fowler",
                "Brewer",
                "Hoffman",
                "Carlson",
                "Silva",
                "Pearson",
                "Holland",
                "Douglas",
                "Fleming",
                "Jensen",
                "Vargas",
                "Byrd",
                "Davidson",
                "Hopkins",
                "May",
                "Terry",
                "Herrera",
                "Wade",
                "Soto",
                "Walters",
                "Curtis",
                "Neal",
                "Caldwell",
                "Lowe",
                "Jennings",
                "Barnett",
                "Graves",
                "Jimenez",
                "Horton",
                "Shelton",
                "Barrett",
                "Obrien",
                "Castro",
                "Sutton",
                "Gregory",
                "McKinney",
                "Lucas",
                "Miles",
                "Craig",
                "Rodriquez",
                "Chambers",
                "Holt",
                "Lambert",
                "Fletcher",
                "Watts",
                "Bates",
                "Hale",
                "Rhodes",
                "Pena",
                "Beck",
                "Newman",
                "Haynes",
                "McDaniel",
                "Mendez",
                "Bush",
                "Vaughn",
                "Parks",
                "Dawson",
                "Santiago",
                "Norris",
                "Hardy",
                "Love",
                "Steele",
                "Curry",
                "Powers",
                "Schultz",
                "Barker",
                "Guzman",
                "Page",
                "Munoz",
                "Ball",
                "Keller",
                "Chandler",
                "Weber",
                "Leonard",
                "Walsh",
                "Lyons",
                "Ramsey",
                "Wolfe",
                "Schneider",
                "Mullins",
                "Benson",
                "Sharp",
                "Bowen",
                "Daniel",
                "Barber",
                "Cummings",
                "Hines",
                "Baldwin",
                "Griffith",
                "Valdez",
                "Hubbard",
                "Salazar",
                "Reeves",
                "Warner",
                "Stevenson",
                "Burgess",
                "Santos",
                "Tate",
                "Cross",
                "Garner",
                "Mann",
                "Mack",
                "Moss",
                "Thornton",
                "Dennis",
                "McGee",
                "Farmer",
                "Delgado",
                "Aguilar",
                "Vega",
                "Glover",
                "Manning",
                "Cohen",
                "Harmon",
                "Rodgers",
                "Robbins",
                "Newton",
                "Todd",
                "Blair",
                "Higgins",
                "Ingram",
                "Reese",
                "Cannon",
                "Strickland",
                "Townsend",
                "Potter",
                "Goodwin",
                "Walton",
                "Rowe",
                "Hampton",
                "Ortega",
                "Patton",
                "Swanson",
                "Joseph",
                "Francis",
                "Goodman",
                "Maldonado",
                "Yates",
                "Becker",
                "Erickson",
                "Hodges",
                "Rios",
                "Conner",
                "Adkins",
                "Webster",
                "Norman",
                "Malone",
                "Hammond",
                "Flowers",
                "Cobb",
                "Moody",
                "Quinn",
                "Blake",
                "Maxwell",
                "Pope",
                "Floyd",
                "Osborne",
                "Paul",
                "McCarthy",
                "Guerrero",
                "Lindsey",
                "Estrada",
                "Sandoval",
                "Gibbs",
                "Tyler",
                "Gross",
                "Fitzgerald",
                "Stokes",
                "Doyle",
                "Sherman",
                "Saunders",
                "Wise",
                "Colon",
                "Gill",
                "Alvarado",
                "Greer",
                "Padilla",
                "Simon",
                "Waters",
                "Nunez",
                "Ballard",
                "Schwartz",
                "McBride",
                "Houston",
                "Christensen",
                "Klein",
                "Pratt",
                "Briggs",
                "Parsons",
                "McLaughlin",
                "Zimmerman",
                "French",
                "Buchanan",
                "Moran",
                "Copeland",
                "Roy",
                "Pittman",
                "Brady",
                "McCormick",
                "Holloway",
                "Brock",
                "Poole",
                "Frank",
                "Logan",
                "Owen",
                "Bass",
                "Marsh",
                "Drake",
                "Wong",
                "Jefferson",
                "Park",
                "Morton",
                "Abbott",
                "Sparks",
                "Patrick",
                "Norton",
                "Huff",
                "Clayton",
                "Massey",
                "Lloyd",
                "Figueroa",
                "Carson",
                "Bowers",
                "Roberson",
                "Barton",
                "Tran",
                "Lamb",
                "Harrington",
                "Casey",
                "Boone",
                "Cortez",
                "Clarke",
                "Mathis",
                "Singleton",
                "Wilkins",
                "Cain",
                "Bryan",
                "Underwood",
                "Hogan",
                "McKenzie",
                "Collier",
                "Luna",
                "Phelps",
                "McGuire",
                "Allison",
                "Bridges",
                "Wilkerson",
                "Nash",
                "Summers",
                "Atkins"
            };

            public static readonly List<Tuple<string, string>> NameSuffixes = new List<Tuple<string, string>>
            {
                {"Doctor of Osteopathic Medicine", "D.O."},
                {"Doctor of Philosophy", "Ph.D."},
                {"Esquire", "Esq."},
                {"Junior", "Jr."},
                {"Juris Doctor", "J.D."},
                {"Master of Arts", "M.A."},
                {"Master of Business Administration", "M.B.A."},
                {"Master of Science", "M.S."},
                {"Medical Doctor", "M.D."},
                {"Senior", "Sr."},
                {"The Third", "III"},
                {"The Fourth", "IV"},
                {"Bachelor of Engineering", "B.E"},
                {"Bachelor of Technology", "B.TECH"}
            };

            public static readonly List<string> Nationalities = new List<string>
            {
                "Afghan",
                "Albanian",
                "Algerian",
                "American",
                "Andorran",
                "Angolan",
                "Antiguans",
                "Argentinean",
                "Armenian",
                "Australian",
                "Austrian",
                "Azerbaijani",
                "Bahami",
                "Bahraini",
                "Bangladeshi",
                "Barbadian",
                "Barbudans",
                "Batswana",
                "Belarusian",
                "Belgian",
                "Belizean",
                "Beninese",
                "Bhutanese",
                "Bolivian",
                "Bosnian",
                "Brazilian",
                "British",
                "Bruneian",
                "Bulgarian",
                "Burkinabe",
                "Burmese",
                "Burundian",
                "Cambodian",
                "Cameroonian",
                "Canadian",
                "Cape Verdean",
                "Central African",
                "Chadian",
                "Chilean",
                "Chinese",
                "Colombian",
                "Comoran",
                "Congolese",
                "Costa Rican",
                "Croatian",
                "Cuban",
                "Cypriot",
                "Czech",
                "Danish",
                "Djibouti",
                "Dominican",
                "Dutch",
                "East Timorese",
                "Ecuadorean",
                "Egyptian",
                "Emirian",
                "Equatorial Guinean",
                "Eritrean",
                "Estonian",
                "Ethiopian",
                "Fijian",
                "Filipino",
                "Finnish",
                "French",
                "Gabonese",
                "Gambian",
                "Georgian",
                "German",
                "Ghanaian",
                "Greek",
                "Grenadian",
                "Guatemalan",
                "Guinea-Bissauan",
                "Guinean",
                "Guyanese",
                "Haitian",
                "Herzegovinian",
                "Honduran",
                "Hungarian",
                "I-Kiribati",
                "Icelander",
                "Indian",
                "Indonesian",
                "Iranian",
                "Iraqi",
                "Irish",
                "Israeli",
                "Italian",
                "Ivorian",
                "Jamaican",
                "Japanese",
                "Jordanian",
                "Kazakhstani",
                "Kenyan",
                "Kittian and Nevisian",
                "Kuwaiti",
                "Kyrgyz",
                "Laotian",
                "Latvian",
                "Lebanese",
                "Liberian",
                "Libyan",
                "Liechtensteiner",
                "Lithuanian",
                "Luxembourger",
                "Macedonian",
                "Malagasy",
                "Malawian",
                "Malaysian",
                "Maldivan",
                "Malian",
                "Maltese",
                "Marshallese",
                "Mauritanian",
                "Mauritian",
                "Mexican",
                "Micronesian",
                "Moldovan",
                "Monacan",
                "Mongolian",
                "Moroccan",
                "Mosotho",
                "Motswana",
                "Mozambican",
                "Namibian",
                "Nauruan",
                "Nepalese",
                "New Zealander",
                "Nicaraguan",
                "Nigerian",
                "Nigerien",
                "North Korean",
                "Northern Irish",
                "Norwegian",
                "Omani",
                "Pakistani",
                "Palauan",
                "Panamanian",
                "Papua New Guinean",
                "Paraguayan",
                "Peruvian",
                "Polish",
                "Portuguese",
                "Qatari",
                "Romani",
                "Russian",
                "Rwandan",
                "Saint Lucian",
                "Salvadoran",
                "Samoan",
                "San Marinese",
                "Sao Tomean",
                "Saudi",
                "Scottish",
                "Senegalese",
                "Serbian",
                "Seychellois",
                "Sierra Leonean",
                "Singaporean",
                "Slovakian",
                "Slovenian",
                "Solomon Islander",
                "Somali",
                "South African",
                "South Korean",
                "Spanish",
                "Sri Lankan",
                "Sudanese",
                "Surinamer",
                "Swazi",
                "Swedish",
                "Swiss",
                "Syrian",
                "Taiwanese",
                "Tajik",
                "Tanzanian",
                "Thai",
                "Togolese",
                "Tongan",
                "Trinidadian or Tobagonian",
                "Tunisian",
                "Turkish",
                "Tuvaluan",
                "Ugandan",
                "Ukrainian",
                "Uruguaya",
                "Uzbekistani",
                "Venezuela",
                "Vietnamese",
                "Wels",
                "Yemenit",
                "Zambia",
                "Zimbabwe"
            };

            public static readonly List<string> Tlds = new List<string>
            {
                "com",
                "org",
                "edu",
                "gov",
                "co.uk",
                "net",
                "io",
                "ac",
                "ad",
                "ae",
                "af",
                "ag",
                "ai",
                "al",
                "am",
                "an",
                "ao",
                "aq",
                "ar",
                "as",
                "at",
                "au",
                "aw",
                "ax",
                "az",
                "ba",
                "bb",
                "bd",
                "be",
                "bf",
                "bg",
                "bh",
                "bi",
                "bj",
                "bm",
                "bn",
                "bo",
                "bq",
                "br",
                "bs",
                "bt",
                "bv",
                "bw",
                "by",
                "bz",
                "ca",
                "cc",
                "cd",
                "cf",
                "cg",
                "ch",
                "ci",
                "ck",
                "cl",
                "cm",
                "cn",
                "co",
                "cr",
                "cu",
                "cv",
                "cw",
                "cx",
                "cy",
                "cz",
                "de",
                "dj",
                "dk",
                "dm",
                "do",
                "dz",
                "ec",
                "ee",
                "eg",
                "eh",
                "er",
                "es",
                "et",
                "eu",
                "fi",
                "fj",
                "fk",
                "fm",
                "fo",
                "fr",
                "ga",
                "gb",
                "gd",
                "ge",
                "gf",
                "gg",
                "gh",
                "gi",
                "gl",
                "gm",
                "gn",
                "gp",
                "gq",
                "gr",
                "gs",
                "gt",
                "gu",
                "gw",
                "gy",
                "hk",
                "hm",
                "hn",
                "hr",
                "ht",
                "hu",
                "id",
                "ie",
                "il",
                "im",
                "in",
                "io",
                "iq",
                "ir",
                "is",
                "it",
                "je",
                "jm",
                "jo",
                "jp",
                "ke",
                "kg",
                "kh",
                "ki",
                "km",
                "kn",
                "kp",
                "kr",
                "kw",
                "ky",
                "kz",
                "la",
                "lb",
                "lc",
                "li",
                "lk",
                "lr",
                "ls",
                "lt",
                "lu",
                "lv",
                "ly",
                "ma",
                "mc",
                "md",
                "me",
                "mg",
                "mh",
                "mk",
                "ml",
                "mm",
                "mn",
                "mo",
                "mp",
                "mq",
                "mr",
                "ms",
                "mt",
                "mu",
                "mv",
                "mw",
                "mx",
                "my",
                "mz",
                "na",
                "nc",
                "ne",
                "nf",
                "ng",
                "ni",
                "nl",
                "no",
                "np",
                "nr",
                "nu",
                "nz",
                "om",
                "pa",
                "pe",
                "pf",
                "pg",
                "ph",
                "pk",
                "pl",
                "pm",
                "pn",
                "pr",
                "ps",
                "pt",
                "pw",
                "py",
                "qa",
                "re",
                "ro",
                "rs",
                "ru",
                "rw",
                "sa",
                "sb",
                "sc",
                "sd",
                "se",
                "sg",
                "sh",
                "si",
                "sj",
                "sk",
                "sl",
                "sm",
                "sn",
                "so",
                "sr",
                "ss",
                "st",
                "su",
                "sv",
                "sx",
                "sy",
                "sz",
                "tc",
                "td",
                "tf",
                "tg",
                "th",
                "tj",
                "tk",
                "tl",
                "tm",
                "tn",
                "to",
                "tp",
                "tr",
                "tt",
                "tv",
                "tw",
                "tz",
                "ua",
                "ug",
                "uk",
                "us",
                "uy",
                "uz",
                "va",
                "vc",
                "ve",
                "vg",
                "vi",
                "vn",
                "vu",
                "wf",
                "ws",
                "ye",
                "yt",
                "za",
                "zm",
                "zw"
            };

            public static readonly List<string> ColorNames = new List<string>
            {
                "AliceBlue",
                "Black",
                "Navy",
                "DarkBlue",
                "MediumBlue",
                "Blue",
                "DarkGreen",
                "Green",
                "Teal",
                "DarkCyan",
                "DeepSkyBlue",
                "DarkTurquoise",
                "MediumSpringGreen",
                "Lime",
                "SpringGreen",
                "Aqua",
                "Cyan",
                "MidnightBlue",
                "DodgerBlue",
                "LightSeaGreen",
                "ForestGreen",
                "SeaGreen",
                "DarkSlateGray",
                "LimeGreen",
                "MediumSeaGreen",
                "Turquoise",
                "RoyalBlue",
                "SteelBlue",
                "DarkSlateBlue",
                "MediumTurquoise",
                "Indigo",
                "DarkOliveGreen",
                "CadetBlue",
                "CornflowerBlue",
                "RebeccaPurple",
                "MediumAquaMarine",
                "DimGray",
                "SlateBlue",
                "OliveDrab",
                "SlateGray",
                "LightSlateGray",
                "MediumSlateBlue",
                "LawnGreen",
                "Chartreuse",
                "Aquamarine",
                "Maroon",
                "Purple",
                "Olive",
                "Gray",
                "SkyBlue",
                "LightSkyBlue",
                "BlueViolet",
                "DarkRed",
                "DarkMagenta",
                "SaddleBrown",
                "Ivory",
                "White",
                "DarkSeaGreen",
                "LightGreen",
                "MediumPurple",
                "DarkViolet",
                "PaleGreen",
                "DarkOrchid",
                "YellowGreen",
                "Sienna",
                "Brown",
                "DarkGray",
                "LightBlue",
                "GreenYellow",
                "PaleTurquoise",
                "LightSteelBlue",
                "PowderBlue",
                "FireBrick",
                "DarkGoldenRod",
                "MediumOrchid",
                "RosyBrown",
                "DarkKhaki",
                "Silver",
                "MediumVioletRed",
                "IndianRed",
                "Peru",
                "Chocolate",
                "Tan",
                "LightGray",
                "Thistle",
                "Orchid",
                "GoldenRod",
                "PaleVioletRed",
                "Crimson",
                "Gainsboro",
                "Plum",
                "BurlyWood",
                "LightCyan",
                "Lavender",
                "DarkSalmon",
                "Violet",
                "PaleGoldenRod",
                "LightCoral",
                "Khaki",
                "AliceBlue",
                "HoneyDew",
                "Azure",
                "SandyBrown",
                "Wheat",
                "Beige",
                "WhiteSmoke",
                "MintCream",
                "GhostWhite",
                "Salmon",
                "AntiqueWhite",
                "Linen",
                "LightGoldenRodYellow",
                "OldLace",
                "Red",
                "Fuchsia",
                "Magenta",
                "DeepPink",
                "OrangeRed",
                "Tomato",
                "HotPink",
                "Coral",
                "DarkOrange",
                "LightSalmon",
                "Orange",
                "LightPink",
                "Pink",
                "Gold",
                "PeachPuff",
                "NavajoWhite",
                "Moccasin",
                "Bisque",
                "MistyRose",
                "BlanchedAlmond",
                "PapayaWhip",
                "LavenderBlush",
                "SeaShell",
                "Cornsilk",
                "LemonChiffon",
                "FloralWhite",
                "Snow",
                "Yellow",
                "LightYellow"
            };

            public static readonly List<KeyValuePair<string, string>> StreetSuffixes = new List
                <KeyValuePair<string, string>>
            {
                {"Avenue", "Ave"},
                {"Boulevard", "Blvd"},
                {"Center", "Ctr"},
                {"Circle", "Cir"},
                {"Court", "Ct"},
                {"Drive", "Dr"},
                {"Extension", "Ext"},
                {"Glen", "Gln"},
                {"Grove", "Grv"},
                {"Heights", "Hts"},
                {"Highway", "Hwy"},
                {"Junction", "Jct"},
                {"Key", "Key"},
                {"Lane", "Ln"},
                {"Loop", "Loop"},
                {"Manor", "Mnr"},
                {"Mill", "Mill"},
                {"Park", "Park"},
                {"Parkway", "Pkwy"},
                {"Pass", "Pass"},
                {"Path", "Path"},
                {"Pike", "Pike"},
                {"Place", "Pl"},
                {"Plaza", "Plz"},
                {"Point", "Pt"},
                {"Ridge", "Rdg"},
                {"River", "Riv"},
                {"Road", "Rd"},
                {"Square", "Sq"},
                {"Street", "St"},
                {"Terrace", "Ter"},
                {"Trail", "Trl"},
                {"Turnpike", "Tpke"},
                {"View", "Vw"},
                {"Way", "Way"}
            };

            public static readonly List<KeyValuePair<string, string>> UsStates = new List<KeyValuePair<string, string>>
            {
                {"Alabama", "AL"},
                {"Alaska", "AK"},
                {"Arizona", "AZ"},
                {"Arkansas", "AR"},
                {"California", "CA"},
                {"Colorado", "CO"},
                {"Connecticut", "CT"},
                {"Delaware", "DE"},
                {"District of Columbia", "DC"},
                {"Florida", "FL"},
                {"Georgia", "GA"},
                {"Hawaii", "HI"},
                {"Idaho", "ID"},
                {"Illinois", "IL"},
                {"Indiana", "IN"},
                {"Iowa", "IA"},
                {"Kansas", "KS"},
                {"Kentucky", "KY"},
                {"Louisiana", "LA"},
                {"Maine", "ME"},
                {"Maryland", "MD"},
                {"Massachusetts", "MA"},
                {"Michigan", "MI"},
                {"Minnesota", "MN"},
                {"Mississippi", "MS"},
                {"Missouri", "MO"},
                {"Montana", "MT"},
                {"Nebraska", "NE"},
                {"Nevada", "NV"},
                {"New Hampshire", "NH"},
                {"New Jersey", "NJ"},
                {"New Mexico", "NM"},
                {"New York", "NY"},
                {"North Carolina", "NC"},
                {"North Dakota", "ND"},
                {"Ohio", "OH"},
                {"Oklahoma", "OK"},
                {"Oregon", "OR"},
                {"Pennsylvania", "PA"},
                {"Rhode Island", "RI"},
                {"South Carolina", "SC"},
                {"South Dakota", "SD"},
                {"Tennessee", "TN"},
                {"Texas", "TX"},
                {"Utah", "UT"},
                {"Vermont", "VT"},
                {"Virginia", "VA"},
                {"Washington", "WA"},
                {"West Virginia", "WV"},
                {"Wisconsin", "WI"},
                {"Wyoming", "WY"}
            };

            public static readonly List<KeyValuePair<string, string>> Countries =
                new List<KeyValuePair<string, string>>
                {
                    {"Afghanistan", "AF"},
                    {"Albania", "AL"},
                    {"Algeria", "DZ"},
                    {"American Samoa", "AS"},
                    {"Andorra", "AD"},
                    {"Angola", "AO"},
                    {"Anguilla", "AI"},
                    {"Antarctica", "AQ"},
                    {"Antigua and Barbuda", "AG"},
                    {"Argentina", "AR"},
                    {"Armenia", "AM"},
                    {"Aruba", "AW"},
                    {"Australia", "AU"},
                    {"Austria", "AT"},
                    {"Azerbaijan", "AZ"},
                    {"Bahamas", "BS"},
                    {"Bahrain", "BH"},
                    {"Bangladesh", "BD"},
                    {"Barbados", "BB"},
                    {"Belarus", "BY"},
                    {"Belgium", "BE"},
                    {"Belize", "BZ"},
                    {"Benin", "BJ"},
                    {"Bermuda", "BM"},
                    {"Bhutan", "BT"},
                    {"Bolivia", "BO"},
                    {"Bosnia and Herzegovina", "BA"},
                    {"Botswana", "BW"},
                    {"Bouvet Island", "BV"},
                    {"Brazil", "BR"},
                    {"British Antarctic Territory", "BQ"},
                    {"British Indian Ocean Territory", "IO"},
                    {"British Virgin Islands", "VG"},
                    {"Brunei", "BN"},
                    {"Bulgaria", "BG"},
                    {"Burkina Faso", "BF"},
                    {"Burundi", "BI"},
                    {"Cambodia", "KH"},
                    {"Cameroon", "CM"},
                    {"Canada", "CA"},
                    {"Canton and Enderbury Islands", "CT"},
                    {"Cape Verde", "CV"},
                    {"Cayman Islands", "KY"},
                    {"Central African Republic", "CF"},
                    {"Chad", "TD"},
                    {"Chile", "CL"},
                    {"China", "CN"},
                    {"Christmas Island", "CX"},
                    {"Cocos [Keeling] Islands", "CC"},
                    {"Colombia", "CO"},
                    {"Comoros", "KM"},
                    {"Congo - Brazzaville", "CG"},
                    {"Congo - Kinshasa", "CD"},
                    {"Cook Islands", "CK"},
                    {"Costa Rica", "CR"},
                    {"Croatia", "HR"},
                    {"Cuba", "CU"},
                    {"Cyprus", "CY"},
                    {"Czech Republic", "CZ"},
                    {"Côte d’Ivoire", "CI"},
                    {"Denmark", "DK"},
                    {"Djibouti", "DJ"},
                    {"Dominica", "DM"},
                    {"Dominican Republic", "DO"},
                    {"Dronning Maud Land", "NQ"},
                    {"East Germany", "DD"},
                    {"Ecuador", "EC"},
                    {"Egypt", "EG"},
                    {"El Salvador", "SV"},
                    {"Equatorial Guinea", "GQ"},
                    {"Eritrea", "ER"},
                    {"Estonia", "EE"},
                    {"Ethiopia", "ET"},
                    {"Falkland Islands", "FK"},
                    {"Faroe Islands", "FO"},
                    {"Fiji", "FJ"},
                    {"Finland", "FI"},
                    {"France", "FR"},
                    {"French Guiana", "GF"},
                    {"French Polynesia", "PF"},
                    {"French Southern Territories", "TF"},
                    {"French Southern and Antarctic Territories", "FQ"},
                    {"Gabon", "GA"},
                    {"Gambia", "GM"},
                    {"Georgia", "GE"},
                    {"Germany", "DE"},
                    {"Ghana", "GH"},
                    {"Gibraltar", "GI"},
                    {"Greece", "GR"},
                    {"Greenland", "GL"},
                    {"Grenada", "GD"},
                    {"Guadeloupe", "GP"},
                    {"Guam", "GU"},
                    {"Guatemala", "GT"},
                    {"Guernsey", "GG"},
                    {"Guinea", "GN"},
                    {"Guinea-Bissau", "GW"},
                    {"Guyana", "GY"},
                    {"Haiti", "HT"},
                    {"Heard Island and McDonald Islands", "HM"},
                    {"Honduras", "HN"},
                    {"Hong Kong SAR China", "HK"},
                    {"Hungary", "HU"},
                    {"Iceland", "IS"},
                    {"India", "IN"},
                    {"Indonesia", "ID"},
                    {"Iran", "IR"},
                    {"Iraq", "IQ"},
                    {"Ireland", "IE"},
                    {"Isle of Man", "IM"},
                    {"Israel", "IL"},
                    {"Italy", "IT"},
                    {"Jamaica", "JM"},
                    {"Japan", "JP"},
                    {"Jersey", "JE"},
                    {"Johnston Island", "JT"},
                    {"Jordan", "JO"},
                    {"Kazakhstan", "KZ"},
                    {"Kenya", "KE"},
                    {"Kiribati", "KI"},
                    {"Kuwait", "KW"},
                    {"Kyrgyzstan", "KG"},
                    {"Laos", "LA"},
                    {"Latvia", "LV"},
                    {"Lebanon", "LB"},
                    {"Lesotho", "LS"},
                    {"Liberia", "LR"},
                    {"Libya", "LY"},
                    {"Liechtenstein", "LI"},
                    {"Lithuania", "LT"},
                    {"Luxembourg", "LU"},
                    {"Macau SAR China", "MO"},
                    {"Macedonia", "MK"},
                    {"Madagascar", "MG"},
                    {"Malawi", "MW"},
                    {"Malaysia", "MY"},
                    {"Maldives", "MV"},
                    {"Mali", "ML"},
                    {"Malta", "MT"},
                    {"Marshall Islands", "MH"},
                    {"Martinique", "MQ"},
                    {"Mauritania", "MR"},
                    {"Mauritius", "MU"},
                    {"Mayotte", "YT"},
                    {"Metropolitan France", "FX"},
                    {"Mexico", "MX"},
                    {"Micronesia", "FM"},
                    {"Midway Islands", "MI"},
                    {"Moldova", "MD"},
                    {"Monaco", "MC"},
                    {"Mongolia", "MN"},
                    {"Montenegro", "ME"},
                    {"Montserrat", "MS"},
                    {"Morocco", "MA"},
                    {"Mozambique", "MZ"},
                    {"Myanmar [Burma]", "MM"},
                    {"Namibia", "NA"},
                    {"Nauru", "NR"},
                    {"Nepal", "NP"},
                    {"Netherlands", "NL"},
                    {"Netherlands Antilles", "AN"},
                    {"Neutral Zone", "NT"},
                    {"New Caledonia", "NC"},
                    {"New Zealand", "NZ"},
                    {"Nicaragua", "NI"},
                    {"Niger", "NE"},
                    {"Nigeria", "NG"},
                    {"Niue", "NU"},
                    {"Norfolk Island", "NF"},
                    {"North Korea", "KP"},
                    {"North Vietnam", "VD"},
                    {"Northern Mariana Islands", "MP"},
                    {"Norway", "NO"},
                    {"Oman", "OM"},
                    {"Pacific Islands Trust Territory", "PC"},
                    {"Pakistan", "PK"},
                    {"Palau", "PW"},
                    {"Palestinian Territories", "PS"},
                    {"Panama", "PA"},
                    {"Panama Canal Zone", "PZ"},
                    {"Papua New Guinea", "PG"},
                    {"Paraguay", "PY"},
                    {"People's Democratic Republic of Yemen", "YD"},
                    {"Peru", "PE"},
                    {"Philippines", "PH"},
                    {"Pitcairn Islands", "PN"},
                    {"Poland", "PL"},
                    {"Portugal", "PT"},
                    {"Puerto Rico", "PR"},
                    {"Qatar", "QA"},
                    {"Romania", "RO"},
                    {"Russia", "RU"},
                    {"Rwanda", "RW"},
                    {"Réunion", "RE"},
                    {"Saint Barthélemy", "BL"},
                    {"Saint Helena", "SH"},
                    {"Saint Kitts and Nevis", "KN"},
                    {"Saint Lucia", "LC"},
                    {"Saint Martin", "MF"},
                    {"Saint Pierre and Miquelon", "PM"},
                    {"Saint Vincent and the Grenadines", "VC"},
                    {"Samoa", "WS"},
                    {"San Marino", "SM"},
                    {"Saudi Arabia", "SA"},
                    {"Senegal", "SN"},
                    {"Serbia", "RS"},
                    {"Serbia and Montenegro", "CS"},
                    {"Seychelles", "SC"},
                    {"Sierra Leone", "SL"},
                    {"Singapore", "SG"},
                    {"Slovakia", "SK"},
                    {"Slovenia", "SI"},
                    {"Solomon Islands", "SB"},
                    {"Somalia", "SO"},
                    {"South Africa", "ZA"},
                    {"South Georgia and the South Sandwich Islands", "GS"},
                    {"South Korea", "KR"},
                    {"Spain", "ES"},
                    {"Sri Lanka", "LK"},
                    {"Sudan", "SD"},
                    {"Suriname", "SR"},
                    {"Svalbard and Jan Mayen", "SJ"},
                    {"Swaziland", "SZ"},
                    {"Sweden", "SE"},
                    {"Switzerland", "CH"},
                    {"Syria", "SY"},
                    {"São Tomé and Príncipe", "ST"},
                    {"Taiwan", "TW"},
                    {"Tajikistan", "TJ"},
                    {"Tanzania", "TZ"},
                    {"Thailand", "TH"},
                    {"Timor-Leste", "TL"},
                    {"Togo", "TG"},
                    {"Tokelau", "TK"},
                    {"Tonga", "TO"},
                    {"Trinidad and Tobago", "TT"},
                    {"Tunisia", "TN"},
                    {"Turkey", "TR"},
                    {"Turkmenistan", "TM"},
                    {"Turks and Caicos Islands", "TC"},
                    {"Tuvalu", "TV"},
                    {"U.S. Minor Outlying Islands", "UM"},
                    {"U.S. Miscellaneous Pacific Islands", "PU"},
                    {"U.S. Virgin Islands", "VI"},
                    {"Uganda", "UG"},
                    {"Ukraine", "UA"},
                    {"Union of Soviet Socialist Republics", "SU"},
                    {"United Arab Emirates", "AE"},
                    {"United Kingdom", "GB"},
                    {"United States", "US"},
                    {"Unknown or Invalid Region", "ZZ"},
                    {"Uruguay", "UY"},
                    {"Uzbekistan", "UZ"},
                    {"Vanuatu", "VU"},
                    {"Vatican City", "VA"},
                    {"Venezuela", "VE"},
                    {"Vietnam", "VN"},
                    {"Wake Island", "WK"},
                    {"Wallis and Futuna", "WF"},
                    {"Western Sahara", "EH"},
                    {"Yemen", "YE"},
                    {"Zambia", "ZM"},
                    {"Zimbabwe", "ZW"},
                    {"Åland Islands", "AX"}
                };

            public static readonly List<Tuple<string, string, string, int>> CcTypes = new List
                <Tuple<string, string, string, int>>
            {
                {"American Express", "amex", "34", 15},
                {"Bankcard", "bankcard", "5610", 16},
                {"China UnionPay", "chinaunion", "62", 16},
                {"Diners Club Carte Blanche", "dccarte", "300", 14},
                {"Diners Club enRoute", "dcenroute", "2014", 15},
                {"Diners Club International", "dcintl", "36", 14},
                {"Diners Club United States & Canada", "dcusc", "54", 16},
                {"Discover Card", "discover", "6011", 16},
                {"InstaPayment", "instapay", "637", 16},
                {"JCB", "jcb", "3528", 16},
                {"Laser", "laser", "6304", 16},
                {"Maestro", "maestro", "5018", 16},
                {"Mastercard", "mc", "51", 16},
                {"Solo", "solo", "6334", 16},
                {"Switch", "switch", "4903", 16},
                {"Visa", "visa", "4", 16},
                {"Visa Electron", "electron", "4026", 16}
            };

            public static readonly List<KeyValuePair<string, string>> CurrenyTypes = new List
                <KeyValuePair<string, string>>
            {
                {"AED", "United Arab Emirates Dirham"},
                {"AFN", "Afghanistan Afghani"},
                {"ALL", "Albania Lek"},
                {"AMD", "Armenia Dram"},
                {"ANG", "Netherlands Antilles Guilder"},
                {"AOA", "Angola Kwanza"},
                {"ARS", "Argentina Peso"},
                {"AUD", "Australia Dollar"},
                {"AWG", "Aruba Guilder"},
                {"AZN", "Azerbaijan New Manat"},
                {"BAM", "Bosnia and Herzegovina Convertible Marka"},
                {"BBD", "Barbados Dollar"},
                {"BDT", "Bangladesh Taka"},
                {"BGN", "Bulgaria Lev"},
                {"BHD", "Bahrain Dinar"},
                {"BIF", "Burundi Franc"},
                {"BMD", "Bermuda Dollar"},
                {"BND", "Brunei Darussalam Dollar"},
                {"BOB", "Bolivia Boliviano"},
                {"BRL", "Brazil Real"},
                {"BSD", "Bahamas Dollar"},
                {"BTN", "Bhutan Ngultrum"},
                {"BWP", "Botswana Pula"},
                {"BYR", "Belarus Ruble"},
                {"BZD", "Belize Dollar"},
                {"CAD", "Canada Dollar"},
                {"CDF", "Congo/Kinshasa Franc"},
                {"CHF", "Switzerland Franc"},
                {"CLP", "Chile Peso"},
                {"CNY", "China Yuan Renminbi"},
                {"COP", "Colombia Peso"},
                {"CRC", "Costa Rica Colon"},
                {"CUC", "Cuba Convertible Peso"},
                {"CUP", "Cuba Peso"},
                {"CVE", "Cape Verde Escudo"},
                {"CZK", "Czech Republic Koruna"},
                {"DJF", "Djibouti Franc"},
                {"DKK", "Denmark Krone"},
                {"DOP", "Dominican Republic Peso"},
                {"DZD", "Algeria Dinar"},
                {"EGP", "Egypt Pound"},
                {"ERN", "Eritrea Nakfa"},
                {"ETB", "Ethiopia Birr"},
                {"EUR", "Euro Member Countries"},
                {"FJD", "Fiji Dollar"},
                {"FKP", "Falkland Islands (Malvinas) Pound"},
                {"GBP", "United Kingdom Pound"},
                {"GEL", "Georgia Lari"},
                {"GGP", "Guernsey Pound"},
                {"GHS", "Ghana Cedi"},
                {"GIP", "Gibraltar Pound"},
                {"GMD", "Gambia Dalasi"},
                {"GNF", "Guinea Franc"},
                {"GTQ", "Guatemala Quetzal"},
                {"GYD", "Guyana Dollar"},
                {"HKD", "Hong Kong Dollar"},
                {"HNL", "Honduras Lempira"},
                {"HRK", "Croatia Kuna"},
                {"HTG", "Haiti Gourde"},
                {"HUF", "Hungary Forint"},
                {"IDR", "Indonesia Rupiah"},
                {"ILS", "Israel Shekel"},
                {"IMP", "Isle of Man Pound"},
                {"INR", "India Rupee"},
                {"IQD", "Iraq Dinar"},
                {"IRR", "Iran Rial"},
                {"ISK", "Iceland Krona"},
                {"JEP", "Jersey Pound"},
                {"JMD", "Jamaica Dollar"},
                {"JOD", "Jordan Dinar"},
                {"JPY", "Japan Yen"},
                {"KES", "Kenya Shilling"},
                {"KGS", "Kyrgyzstan Som"},
                {"KHR", "Cambodia Riel"},
                {"KMF", "Comoros Franc"},
                {"KPW", "Korea (North) Won"},
                {"KRW", "Korea (South) Won"},
                {"KWD", "Kuwait Dinar"},
                {"KYD", "Cayman Islands Dollar"},
                {"KZT", "Kazakhstan Tenge"},
                {"LAK", "Laos Kip"},
                {"LBP", "Lebanon Pound"},
                {"LKR", "Sri Lanka Rupee"},
                {"LRD", "Liberia Dollar"},
                {"LSL", "Lesotho Loti"},
                {"LTL", "Lithuania Litas"},
                {"LYD", "Libya Dinar"},
                {"MAD", "Morocco Dirham"},
                {"MDL", "Moldova Leu"},
                {"MGA", "Madagascar Ariary"},
                {"MKD", "Macedonia Denar"},
                {"MMK", "Myanmar (Burma) Kyat"},
                {"MNT", "Mongolia Tughrik"},
                {"MOP", "Macau Pataca"},
                {"MRO", "Mauritania Ouguiya"},
                {"MUR", "Mauritius Rupee"},
                {"MVR", "Maldives (Maldive Islands) Rufiyaa"},
                {"MWK", "Malawi Kwacha"},
                {"MXN", "Mexico Peso"},
                {"MYR", "Malaysia Ringgit"},
                {"MZN", "Mozambique Metical"},
                {"NAD", "Namibia Dollar"},
                {"NGN", "Nigeria Naira"},
                {"NIO", "Nicaragua Cordoba"},
                {"NOK", "Norway Krone"},
                {"NPR", "Nepal Rupee"},
                {"NZD", "New Zealand Dollar"},
                {"OMR", "Oman Rial"},
                {"PAB", "Panama Balboa"},
                {"PEN", "Peru Nuevo Sol"},
                {"PGK", "Papua New Guinea Kina"},
                {"PHP", "Philippines Peso"},
                {"PKR", "Pakistan Rupee"},
                {"PLN", "Poland Zloty"},
                {"PYG", "Paraguay Guarani"},
                {"QAR", "Qatar Riyal"},
                {"RON", "Romania New Leu"},
                {"RSD", "Serbia Dinar"},
                {"RUB", "Russia Ruble"},
                {"RWF", "Rwanda Franc"},
                {"SAR", "Saudi Arabia Riyal"},
                {"SBD", "Solomon Islands Dollar"},
                {"SCR", "Seychelles Rupee"},
                {"SDG", "Sudan Pound"},
                {"SEK", "Sweden Krona"},
                {"SGD", "Singapore Dollar"},
                {"SHP", "Saint Helena Pound"},
                {"SLL", "Sierra Leone Leone"},
                {"SOS", "Somalia Shilling"},
                {"SPL", "Seborga Luigino"},
                {"SRD", "Suriname Dollar"},
                {"STD", "São Tomé and Príncipe Dobra"},
                {"SVC", "El Salvador Colon"},
                {"SYP", "Syria Pound"},
                {"SZL", "Swaziland Lilangeni"},
                {"THB", "Thailand Baht"},
                {"TJS", "Tajikistan Somoni"},
                {"TMT", "Turkmenistan Manat"},
                {"TND", "Tunisia Dinar"},
                {"TOP", "Tonga Pa\'anga"},
                {"TRY", "Turkey Lira"},
                {"TTD", "Trinidad and Tobago Dollar"},
                {"TVD", "Tuvalu Dollar"},
                {"TWD", "Taiwan New Dollar"},
                {"TZS", "Tanzania Shilling"},
                {"UAH", "Ukraine Hryvnia"},
                {"UGX", "Uganda Shilling"},
                {"USD", "United States Dollar"},
                {"UYU", "Uruguay Peso"},
                {"UZS", "Uzbekistan Som"},
                {"VEF", "Venezuela Bolivar"},
                {"VND", "Viet Nam Dong"},
                {"VUV", "Vanuatu Vatu"},
                {"WST", "Samoa Tala"},
                {"XAF", "Communauté Financière Africaine (BEAC) CFA Franc BEAC"},
                {"XCD", "East Caribbean Dollar"},
                {"XDR", "International Monetary Fund (IMF) Special Drawing Rights"},
                {"XOF", "Communauté Financière Africaine (BCEAO) Franc"},
                {"XPF", "Comptoirs Français du Pacifique (CFP) Franc"},
                {"YER", "Yemen Rial"},
                {"ZAR", "South Africa Rand"},
                {"ZMW", "Zambia Kwacha"},
                {"ZWD", "Zimbabwe Dollar"}
            };
        }
    }
}
